# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7a8c41767fb6ce35881224efea4074c6dcfd0b1f37cc5812f49351255047a00ddc07c88df1d189e7e322734ec09f06f6c16963a6ba1a8a8b3e2d223d5f92dd4

test:
  secret_key_base: 3be2ca07a63cc1815b23467ccbabaf34ad5f85433e29750a626de67fa80111ea1fb8a398a4035c5c77828890e37c1c2ea3f4d98bd0f0f9cb244bc801eea1d7e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
